import { PropsWithChildren } from 'react';
import { ToastContainer } from 'react-toastify';
import type { Metadata, NextPage } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import { getSession } from '@/modules/auth/api/operations/get-session';
import { AuthProvider } from '@/modules/auth/context/auth.context';
import './globals.css';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<PropsWithChildren> = async ({ children }) => {
  const session = await getSession();

  return (
    <AuthProvider session={session}>
      <html lang="en" className="dark">
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          <ToastContainer />
          <div className="flex min-h-screen flex-col items-center justify-between p-24">
            <div className="flex items-start flex-col flex-grow w-full max-w-screen-md">{children}</div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
};

export default RootLayout;
